image: mono:5.8

build:
    stage: build
    script:
        - nuget restore
        - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" VirtualDesktopHotkeyHelper.sln
    artifacts:
        name: "VirtualDesktopHotkeyHelper-$CI_COMMIT_REF_NAME"
        paths:
        - /builds/rockschtar/VirutalDesktopHotkeyHelper/VirtualDesktopLeft/bin/Release
        - /builds/rockschtar/VirutalDesktopHotkeyHelper/VirtualDesktopLeftRight/bin/Release
        - /builds/rockschtar/VirutalDesktopHotkeyHelper/VirtualDesktopRight/bin/Release
        - /builds/rockschtar/VirutalDesktopHotkeyHelper/VirtualDesktopToggle/bin/Release